# Generated by Django 2.0.13 on 2019-06-24 17:29

from django.db import migrations, models
import ordenes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(max_length=20)),
                ('entrada', models.CharField(max_length=25)),
                ('fecha', models.DateField()),
                ('orden', models.ImageField(upload_to=ordenes.models.PathAndRename('imgs_ordenes/'))),
            ],
        ),
    ]
