# Generated by Django 2.0.13 on 2019-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(max_length=20)),
                ('entrada', models.CharField(max_length=25)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('orden', models.CharField(max_length=25)),
            ],
        ),
    ]
