# Generated by Django 2.0.13 on 2019-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='orden',
            field=models.ImageField(upload_to=''),
        ),
    ]
